//! Functions to parse files generated by FHI-aims
/*
 */
#ifndef READ_AIMS_H
#define READ_AIMS_H

#include <string>
#include "meanfield.h"
#include "ri.h"
using std::string;

void READ_AIMS_BAND(const string &file_path, MeanField &mf);
void READ_AIMS_EIGENVECTOR(const string &dir_path, MeanField &mf);
void handle_KS_file(const string &file_path, MeanField &mf);

void read_aims(MeanField &mf);

#endif // !READ_AIMS_H
