//! Functions to parse files generated by FHI-aims
/*
 */
#ifndef READ_DATA_H
#define READ_DATA_H

#include <string>
#include <vector>

#include "../src/core/ri.h"
#include "../src/math/matrix.h"
#include "../src/math/vector3_order.h"
#include "librpa.hpp"

using std::string;
using librpa_int::matrix;
using librpa_int::atpair_t;
using librpa_int::Vector3_Order;
using librpa_int::atpair_R_mat_t;

/*!
 * @brief Read occupation numbers and eigenvalues of SCF calculation
 */
void read_scf_occ_eigenvalues(const string &file_path);

/*!
 * @brief Read exchange-correlation potential
 *
 * @param[in] file_path   data file path
 * @return    status code, 0 for succesful read, 1 with error
 */
int read_vxc(const string &file_path, std::vector<matrix> &vxc);

int read_eigenvector(const string &dir_path);

// high-level reader for RI coefficients and bare Coulomb interactions
void read_ri(const string &dir_path, librpa::ParallelRouting &routing);

size_t read_Cs(const string &dir_path, double threshold, const std::vector<atpair_t> &local_atpair);

size_t read_Cs_evenly_distribute(const string &dir_path, double threshold, int myid, int nprocs);

size_t read_Vq_full(const string &dir_path, const string &vq_fprefix, bool is_cut_coulomb);

size_t read_Vq_row(const string &dir_path, const string &vq_fprefix, double threshold,
                   const std::vector<atpair_t> &local_atpair, bool is_cut_coulomb);

void read_stru(const std::string &file_path);

void read_bz_sampling(const std::string &file_path);

void read_basis(const std::string &file_path);

void read_dielec_func(const string &file_path, std::vector<double> &omegas,
                      std::vector<double> &dielec_func_imagfreq);

void erase_Cs_from_local_atp(atpair_R_mat_t &Cs, std::vector<atpair_t> &local_atpair);

void get_natom_ncell_from_first_Cs_file(int &n_atom, int &n_cell, const string &dir_path);

void read_band_kpath_info(const string &file_path);

void read_band_meanfield_data(const string &dir_path);

std::vector<matrix> read_vxc_band(const string &dir_path, int n_states, int n_spin, int n_kpoints_band);

//! Read ELSI CSC format matrix file
void read_elsi_csc(const string &file_path, bool save_row_major, std::vector<double> &mat, int &n_basis, bool &is_real);
#endif // !READ_DATA_H
